### ISSUE TITLE
PWA firebase integration 

### ISSUE THREAD

**Issue by bensalcie** [pwafire/pwafireapp#5]
Nice work from author, please do more tutorials on how to integrate PWA with firebase

**Comment by mayeedwin** [comment]
Hey @bensalcie , we have an awesome codelab on [cloud firestore](https://pwafire.org/developer/codelabs/cloud-firestore-for-web/) and [firebase relatime database](https://pwafire.org/developer/codelabs/firebase-realtime-database/). Check them out ! Cheers! Am going to close this issue up in 30 Minutes!
