### ISSUE TITLE
Empty page on ios 12.3

### ISSUE THREAD

**Issue by tiptronic** [pwafire/pwafireapp#7]
Running the demo app only shows a blank page 
iphone X / ios 12.3

**To Reproduce**
Click 'View Demo App'

**Comment by mayeedwin** [comment]
@tiptronic , any screenshot with you ? which page exactly if any?

**Comment by tiptronic** [comment]
https://pwafireapp.firebaseapp.com

![image](https://user-images.githubusercontent.com/80752/58383439-062fc180-7fd7-11e9-98f3-7b5b091a68ed.png)

Same thing from Safari and Chrome on my Mac 10.14.5

**Comment by tiptronic** [comment]
That's all what gets added to the DOM:

`<html><head></head><body></body></html>`

**Comment by mayeedwin** [comment]
Oh yeah, just checked it, might be some breakpoint on last deployment. Thank you for the issue.

**Comment by mayeedwin** [comment]
## We are creating a new version
Check the [codelab available here](https://pwafire.org/developer/codelabs/get-started-with-pwafireapp/) to use the previous version of the sample app
